
name: Go Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
      go-version: '>=1.17.0' # The Go version to download (if necessary) and use.

    - name: Build and test
      run: |                         
        go build
        go mod init 
        go test -v deck_test.go    

    - name: Run Security Scan
      run: gosec ./...
